#server:
#  port: 8200
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: BookService
  cloud:
    config:
      uri: http://localhost:8888
      name: BookService
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#  swagger-ui:
#    path: /swagger-ui.html